config/routes.rb
Rails.application.routes.draw do
  resources :person_promotions
  resources :promotions
  resources :lecture_promotions
  devise_for :person, controllers: {
    sessions: 'person/sessions',
    registrations: 'person/registrations'
  }

  get 'lectures/myLectures'
  get 'grades/myGrades'


  # change the path to the sign in page
=begin
  devise_scope :person do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
=end
  # get 'semesters/index'
  # get 'semesters/show'
  # get 'semesters/edit'
  # get 'semesters/new'
  # get 'grades/index'
  # get 'grades/show'
  # get 'grades/edit'
  # get 'grades/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :semesters
  resources :lectures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lectures
  validates :name, presence: true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :semester
  belongs_to :promotion
  belongs_to :student, class_name: "Person"
  belongs_to :teacher, class_name: "Person"
  has_many :lecture_grades
  has_many :lectures, through: :lecture_grades

  validates :result, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 6 }
  validates :weight, presence: true

end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :category
  has_many :lecture_promotions
  has_many :promotions, through: :lecture_promotions
  has_many :lecture_grades
  has_many :grades, through: :lecture_grades

  validates :name, presence: true
  validates :description, presence: true
end

app/models/lecture_grade.rb
class LectureGrade < ApplicationRecord
  belongs_to :lecture
  belongs_to :grade
end

app/models/lecture_promotion.rb
class LecturePromotion < ApplicationRecord
  belongs_to :lecture
  belongs_to :promotion
  belongs_to :semester
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :person_promotions
  has_many :promotions, through: :person_promotions
  has_many :student_grades, class_name: "Grade", foreign_key: "student_id"
  has_many :teacher_grades, class_name: "Grade", foreign_key: "teacher_id"
  has_many :teacher_promotions, class_name: "Promotion", foreign_key: "teacher_id"

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
  validates :type_person_id, presence: true

  def fullname
    "#{lastname} #{firstname}"
  end
end

app/models/person_promotion.rb
class PersonPromotion < ApplicationRecord
  belongs_to :promotion
  belongs_to :person
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :teacher, class_name: 'Person', foreign_key: 'teacher_id'
  has_many :person_promotions
  has_many :people, through: :person_promotions
  has_many :grades
  has_many :lecture_promotions
  has_many :lectures, through: :lecture_promotions

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :grades

  validates :name, presence: true
end

app/models/type_person.rb
class TypePerson < ApplicationRecord
  has_many :people

  validates :name, presence: true
  validates :slug, presence: true
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def myGrades
    @myGrades = Grade.where(student_id: current_person.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_person!, except: [:login]
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

  def index
    @lectures = Lecture.all
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)
    if @lecture.save
      redirect_to lectures_path
    else
      render 'index'
    end

  end
  def myLectures
    @myLectures = LecturePromotion.where(person_id: current_person.id)
  end

  def lecture_params
    params.require(:lecture).permit(:name, :description, :category_id)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: %i[ show edit update destroy ]

  # GET /promotions or /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1 or /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions or /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to promotion_url(@promotion), notice: "Promotion was successfully created." }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1 or /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to promotion_url(@promotion), notice: "Promotion was successfully updated." }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1 or /promotions/1.json
  def destroy
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url, notice: "Promotion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def promotion_params
      params.require(:promotion).permit(:name, :start_date, :end_date, :teacher_id)
    end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  def index
    @semesters = Semester.all
  end

  def show
    @semester = Semester.find(params[:id])
  end

  def edit

  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/person_promotions_helper.rb
module PersonPromotionsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/grades/myGrades.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Names</th>
    <th scope="col">Results</th>
    <th scope="col">Weight</th>
    <th scope="col">Date</th>
    <th scope="col">Semester</th>
    <th scope="col">Promotion</th>
    <th scope="col">Teacher</th>
  </tr>
  </thead>
  <tbody>
  <% @myGrades.each do |grade| %>
    <tr>
      <th scope="row"><%= grade.id %></th>
      <td><%= grade.name %></td>
      <td><%= grade.result %></td>
      <td><%= grade.weight %> %</td>
      <td><%= grade.date %></td>
      <td><%= Semester.find(grade.semester_id).name %></td>
      <td><%= Promotion.find(grade.promotion_id).name %></td>
      <td><%= Person.find(grade.teacher_id).fullname %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/lectures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lectures</h1>
<%= link_to "New", new_lecture_path, class: "btn btn-success" %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Category name</th>
  </tr>
  </thead>
  <tbody>
  <% @lectures.each do |lecture| %>
    <tr>
      <th scope="row"><%= lecture.id %></th>
      <td><%= lecture.name %></td>
      <td><%= lecture.description %></td>
      <td><%= Category.find(lecture.category_id).name %></td>
      <td><%= link_to "Show", lecture_path(lecture), class: "btn btn-warning" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/lectures/myLectures.html.erb
<p style="color: green"><%= notice %></p>

<h1>My lectures</h1>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Promotion</th>
    <th scope="col">Semestre</th>
  </tr>
  </thead>
  <tbody>
  <% @myLectures.each do |lecture| %>
    <tr>
      <th scope="row"><%= lecture.id %></th>
      <td><%= Lecture.find(lecture.lecture_id).name %></td>
      <td><%= Promotion.find(lecture.promotion_id).name %></td>
      <td><%= Semester.find(lecture.semester_id).name %></td>
      <td><%= link_to "Show", lecture_path(lecture), class: "btn btn-warning" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/lectures/new.html.erb
<%= form_with model: @lecture do |form| %>
  <div class="form-group">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>
  <div class="form-group">
    <%= form.label :description, "Description" %>
    <%= form.text_field :description, class: "form-control", placeholder: "Enter description"%>
  </div>
  <div class="form-group">
    <%= form.label :category_id, "Category" %>
    <%= form.select :category_id, options_for_select(Category.all.map { |r| [r.name, r.id] }), {}, class: "form-control"%>
  </div>
  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/lectures/show.html.erb
<div>
  <p>
    <strong>Name :</strong>
    <%= @lecture.name %></span>
  </p>
  <p>
    <strong for="description">Description :</strong>
    <%= @lecture.description %></span>
  </p>
  <p>
    <strong for="category">Category :</strong>
    <%= Category.find(@lecture.category_id).name %></span>
  </p>
  <p>
    <strong for="Promotions">Promotions :</strong>
  <p>
    <% @lecture.promotions.each do |promotion| %>
    <p>
      <%= promotion.name %>
    </p>
  <% end %>
  </p>
  <%= link_to "Add promotion", new_lecture_promotion_path, class: "btn btn-success" %>
  </p>
</div>

app/views/promotions/_form.html.erb
<%= form_with(model: promotion) do |form| %>
  <% if promotion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
        <% promotion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date, start_year: 1800, end_year: Time.now.year, class: "form-select" %>
  </div>

  <div class="form-group">
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date, start_year: 1800, end_year: Time.now.year, class: "form-select" %>
  </div>

  <div class="form-group">
    <%= form.label :teacher_id, style: "display: block" %>
    <%= form.select :teacher_id, options_for_select(Person.where(type_person_id: TypePerson.find_by(slug: 'TEA')).map { |r| [r.fullname, r.id] }), {}, class: "form-control" %>
  </div>

  <div><%= form.submit "Submit", class: "btn btn-primary" %></div>
<% end %>

app/views/promotions/_promotion.html.erb
<div id="<%= dom_id promotion %>">
  <p>
    <strong>Name:</strong>
    <%= promotion.name %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= promotion.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= promotion.end_date %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= Person.find(promotion.teacher_id).fullname %>
  <p>
    <strong>Students:</strong>
    <% PersonPromotion.where(promotion_id: promotion.id).each do |person_promotion| %>
    <p>
      <%= Person.find(person_promotion.person_id).fullname %>
    </p>
  <% end %>
  <%= link_to "Add student", new_person_promotion_path, class: "btn btn-success" %>
  </p>
</div>

app/views/promotions/edit.html.erb
<h1>Editing promotion</h1>

<%= render "form", promotion: @promotion %>

<br>

<div>
  <%= link_to "Show this promotion", @promotion %> |
  <%= link_to "Back to promotions", promotions_path %>
</div>

app/views/promotions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Promotions</h1>
<%= link_to "New", new_promotion_path, class: "btn btn-success" %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Start Date</th>
    <th scope="col">End Date</th>
    <th scope="col">Teacher</th>
  </tr>
  </thead>
  <tbody>
  <% @promotions.each do |promotion| %>
    <tr>
      <th scope="row"><%= promotion.id %></th>
      <td><%= promotion.name %></td>
      <td><%= promotion.start_date %></td>
      <td><%= promotion.end_date %></td>
      <td><%= Person.find(promotion.teacher_id).fullname %></td>
      <td><%= link_to "Show", promotion_path(promotion), class: "btn btn-warning" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render "form", promotion: @promotion %>

<br>

<div>
  <%= link_to "Back to promotions", promotions_path %>
</div>

app/views/promotions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @promotion %>

<div>
  <%= link_to "Edit this promotion", edit_promotion_path(@promotion) %> |
  <%= link_to "Back to promotions", promotions_path %>

  <%= button_to "Destroy this promotion", @promotion, method: :delete %>
</div>

app/views/semesters/edit.html.erb
<h1>Semesters#edit</h1>
<p>Find me in app/views/semesters/edit.html.erb</p>

app/views/semesters/index.html.erb
<h1>Liste of semesters</h1>

<ul>
  <% @semesters.each do |semester|  %>
    <li>
      <%= link_to semester.name, semester%>
    </li>
  <% end %>
</ul>

app/views/semesters/new.html.erb
<h1>Semesters#new</h1>
<p>Find me in app/views/semesters/new.html.erb</p>

app/views/semesters/show.html.erb
<h1>Semesters#show</h1>
<p>Find me in app/views/semesters/show.html.erb</p>