config/routes.rb
Rails.application.routes.draw do
  resources :person_promotions
  resources :promotions
  resources :lecture_promotions
  devise_for :person, controllers: {
    sessions: 'person/sessions',
    registrations: 'person/registrations'
  }

  get 'lectures/myLectures'
  get 'grades/myGrades'


  # change the path to the sign in page
=begin
  devise_scope :person do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
=end
  # get 'semesters/index'
  # get 'semesters/show'
  # get 'semesters/edit'
  # get 'semesters/new'
  # get 'grades/index'
  # get 'grades/show'
  # get 'grades/edit'
  # get 'grades/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :semesters
  resources :lectures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lectures
  validates :name, presence: true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :semester
  belongs_to :promotion
  belongs_to :student, class_name: "Person"
  belongs_to :teacher, class_name: "Person"
  has_many :lecture_grades
  has_many :lectures, through: :lecture_grades

  validates :result, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 6 }
  validates :weight, presence: true

end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :category
  has_many :lecture_promotions
  has_many :promotions, through: :lecture_promotions
  has_many :lecture_grades
  has_many :grades, through: :lecture_grades

  validates :name, presence: true
  validates :description, presence: true
end

app/models/lecture_grade.rb
class LectureGrade < ApplicationRecord
  belongs_to :lecture
  belongs_to :grade
end

app/models/lecture_promotion.rb
class LecturePromotion < ApplicationRecord
  belongs_to :lecture
  belongs_to :promotion
  belongs_to :semester
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :person_promotions
  has_many :promotions, through: :person_promotions
  has_many :student_grades, class_name: "Grade", foreign_key: "student_id"
  has_many :teacher_grades, class_name: "Grade", foreign_key: "teacher_id"
  has_many :teacher_promotions, class_name: "Promotion", foreign_key: "teacher_id"

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
  validates :type_person_id, presence: true

  def fullname
    "#{lastname} #{firstname}"
  end
end

app/models/person_promotion.rb
class PersonPromotion < ApplicationRecord
  belongs_to :promotion
  belongs_to :person
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :teacher, class_name: 'Person', foreign_key: 'teacher_id'
  has_many :person_promotions
  has_many :people, through: :person_promotions
  has_many :grades
  has_many :lecture_promotions
  has_many :lectures, through: :lecture_promotions

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :grades

  validates :name, presence: true
end

app/models/type_person.rb
class TypePerson < ApplicationRecord
  has_many :people

  validates :name, presence: true
  validates :slug, presence: true
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def myGrades
    @myGrades = Grade.where(student_id: current_person.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_person!, except: [:login]
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

  def index
    @lectures = Lecture.all
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)
    if @lecture.save
      redirect_to lectures_path
    else
      render 'index'
    end

  end
  def myLectures
    @myLectures = LecturePromotion.where(person_id: current_person.id)
  end

  def lecture_params
    params.require(:lecture).permit(:name, :description, :category_id)
  end
end

app/controllers/person_promotions_controller.rb
class PersonPromotionsController < ApplicationController
  before_action :set_person_promotion, only: %i[ show edit update destroy ]

  # GET /person_promotions or /person_promotions.json
  def index
    @person_promotions = PersonPromotion.all
  end

  # GET /person_promotions/1 or /person_promotions/1.json
  def show
  end

  # GET /person_promotions/new
  def new
    @person_promotion = PersonPromotion.new
  end

  # GET /person_promotions/1/edit
  def edit
  end

  # POST /person_promotions or /person_promotions.json
  def create
    @person_promotion = PersonPromotion.new(person_promotion_params)

    respond_to do |format|
      if @person_promotion.save
        format.html { redirect_to person_promotion_url(@person_promotion), notice: "Person promotion was successfully created." }
        format.json { render :show, status: :created, location: @person_promotion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /person_promotions/1 or /person_promotions/1.json
  def update
    respond_to do |format|
      if @person_promotion.update(person_promotion_params)
        format.html { redirect_to person_promotion_url(@person_promotion), notice: "Person promotion was successfully updated." }
        format.json { render :show, status: :ok, location: @person_promotion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /person_promotions/1 or /person_promotions/1.json
  def destroy
    @person_promotion.destroy

    respond_to do |format|
      format.html { redirect_to person_promotions_url, notice: "Person promotion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person_promotion
      @person_promotion = PersonPromotion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_promotion_params
      params.require(:person_promotion).permit(:promotion_id, :person_id)
    end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  def index
    @semesters = Semester.all
  end

  def show
    @semester = Semester.find(params[:id])
  end

  def edit

  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/person_promotions_helper.rb
module PersonPromotionsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/person_promotions/_form.html.erb
<%= form_with(model: person_promotion) do |form| %>
  <% if person_promotion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person_promotion.errors.count, "error") %> prohibited this person_promotion from being saved:</h2>

      <ul>
        <% person_promotion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :promotion_id, style: "display: block" %>
    <%= form.select :promotion_id, options_for_select(Promotion.all.map { |r| [r.name, r.id] }), {}, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :person_id, style: "display: block" %>
    <%= form.select :person_id, options_for_select(Person.where(type_person_id: TypePerson.find_by(slug: 'STU')).map { |r| [r.fullname, r.id] }), {}, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/person_promotions/_person_promotion.html.erb
<div id="<%= dom_id person_promotion %>">
  <p>
    <strong>Promotion:</strong>
    <%= person_promotion.promotion_id %>
  </p>

  <p>
    <strong>Person:</strong>
    <%= person_promotion.person_id %>
  </p>

</div>

app/views/person_promotions/edit.html.erb
<h1>Editing person promotion</h1>

<%= render "form", person_promotion: @person_promotion %>

<br>

<div>
  <%= link_to "Show this person promotion", @person_promotion %> |
  <%= link_to "Back to person promotions", person_promotions_path %>
</div>

app/views/person_promotions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Person promotions</h1>

<div id="person_promotions">
  <% @person_promotions.each do |person_promotion| %>
    <%= render person_promotion %>
    <p>
      <%= link_to "Show this person promotion", person_promotion %>
    </p>
  <% end %>
</div>

<%= link_to "New person promotion", new_person_promotion_path %>

app/views/person_promotions/new.html.erb
<h1>New person promotion</h1>

<%= render "form", person_promotion: @person_promotion %>

<br>

<div>
  <%= link_to "Back to person promotions", person_promotions_path %>
</div>

app/views/person_promotions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person_promotion %>

<div>
  <%= link_to "Edit this person promotion", edit_person_promotion_path(@person_promotion) %> |
  <%= link_to "Back to person promotions", person_promotions_path %>

  <%= button_to "Destroy this person promotion", @person_promotion, method: :delete %>
</div>