config/routes.rb
Rails.application.routes.draw do
  resources :person_promotions
  resources :promotions
  resources :lecture_promotions
  devise_for :person, controllers: {
    sessions: 'person/sessions',
    registrations: 'person/registrations'
  }

  get 'lectures/myLectures'
  get 'grades/myGrades'


  # change the path to the sign in page
=begin
  devise_scope :person do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
=end
  # get 'semesters/index'
  # get 'semesters/show'
  # get 'semesters/edit'
  # get 'semesters/new'
  # get 'grades/index'
  # get 'grades/show'
  # get 'grades/edit'
  # get 'grades/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :semesters
  resources :lectures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lectures
  validates :name, presence: true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :semester
  belongs_to :promotion
  belongs_to :student, class_name: "Person"
  belongs_to :teacher, class_name: "Person"
  has_many :lecture_grades
  has_many :lectures, through: :lecture_grades

  validates :result, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 6 }
  validates :weight, presence: true

end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :category
  has_many :lecture_promotions
  has_many :promotions, through: :lecture_promotions
  has_many :lecture_grades
  has_many :grades, through: :lecture_grades

  validates :name, presence: true
  validates :description, presence: true
end

app/models/lecture_grade.rb
class LectureGrade < ApplicationRecord
  belongs_to :lecture
  belongs_to :grade
end

app/models/lecture_promotion.rb
class LecturePromotion < ApplicationRecord
  belongs_to :lecture
  belongs_to :promotion
  belongs_to :semester
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :person_promotions
  has_many :promotions, through: :person_promotions
  has_many :student_grades, class_name: "Grade", foreign_key: "student_id"
  has_many :teacher_grades, class_name: "Grade", foreign_key: "teacher_id"
  has_many :teacher_promotions, class_name: "Promotion", foreign_key: "teacher_id"

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
  validates :type_person_id, presence: true

  def fullname
    "#{lastname} #{firstname}"
  end
end

app/models/person_promotion.rb
class PersonPromotion < ApplicationRecord
  belongs_to :promotion
  belongs_to :person
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :teacher, class_name: 'Person', foreign_key: 'teacher_id'
  has_many :person_promotions
  has_many :people, through: :person_promotions
  has_many :grades
  has_many :lecture_promotions
  has_many :lectures, through: :lecture_promotions

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :grades

  validates :name, presence: true
end

app/models/type_person.rb
class TypePerson < ApplicationRecord
  has_many :people

  validates :name, presence: true
  validates :slug, presence: true
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def myGrades
    @myGrades = Grade.where(student_id: current_person.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_person!, except: [:login]
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

  def index
    @lectures = Lecture.all
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)
    if @lecture.save
      redirect_to lectures_path
    else
      render 'index'
    end

  end
  def myLectures
    @myLectures = LecturePromotion.where(person_id: current_person.id)
  end

  def lecture_params
    params.require(:lecture).permit(:name, :description, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ASP1Gifi</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar navbar-dark bg-dark navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <% if person_signed_in? %>
          <% if current_person.type_person_id === 1 %>
            <li class="nav-item">
              <%= link_to "My grades", grades_myGrades_path, class: "nav-link active" %>
            </li>
          <% end %>
          <% if current_person.type_person_id === 2 %>
            <li class="nav-item">
              <%= link_to "My Lectures", lectures_myLectures_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Lectures", lectures_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Promotions", promotions_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <% if person_signed_in? %>
        <span class="navbar-text">
          Welcome <%= current_person.fullname %>
          as <%= TypePerson.find(current_person.type_person_id).name %>
        </span>
        <%= form_with url: "/person/sign_out", method: :delete do |form| %>
          <%= form.submit "Logout", class: "btn btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>
<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>